stages:
  - build
  - deploy

build:
  image: registry.yunmotec.com:1443/docker:latest
  tags:
    - front
    - nodejs
  services:
    - registry.yunmotec.com:1443/docker:dind
  stage: build
  only:
    - develop
    - /^Staging-.*$/
    - /^Release-.*$/
  script:
    # - export DOCKER_HOST="tcp://localhost:2375"
    - docker build --pull --build-arg BUILD_ENV=build --build-arg ENV=$CI_COMMIT_REF_NAME -t "registry.yunmotec.com:1443/pds-front:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA" .
    - docker push "registry.yunmotec.com:1443/pds-front:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

deploy dev:
  tags:
    - front
    - nodejs
  stage: deploy
  image: registry.yunmotec.com:1443/helm
  only:
    - develop
  script:
    - mkdir .kube  && echo $kuber_config | base64 -d > .kube/config && export KUBECONFIG=$(pwd)/.kube/config
    - cd ci/helm && helm upgrade -f values-dev.yaml --set image.tag=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA --install --namespace procuratorrate pds-front-dev .

deploy qa:
  tags:
    - front
    - nodejs
  stage: deploy
  image: registry.yunmotec.com:1443/helm
  only:
    - /^Staging-.*$/
  except:
    - branches
  script:
    - mkdir .kube  && echo $kuber_config | base64 -d > .kube/config && export KUBECONFIG=$(pwd)/.kube/config
    - cd ci/helm && helm upgrade -f values-qa.yaml --set image.tag=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA --install --namespace procuratorrate  pds-front-qa .