# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.yunmotec.com:1443/emes-management-customer-new
  pullPolicy: Always

nameOverride: "dev"
fullnameOverride: "emescustomerdev"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  }
  hosts:
    - host: mems-customer-dev.yunmotec.net
      paths: ["/"]
resources: {}

persistence:
    enabled: true
    claimName: memsserverdev

