# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.yunmotec.com:1443/pds-front
  pullPolicy: Always

nameOverride: "qa"
fullnameOverride: "pdsfrontqa"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: 100m,
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 600s,
    nginx.ingress.kubernetes.io/proxy-send-timeout: 600s,
    nginx.ingress.kubernetes.io/proxy-read-timeout: 600s
  }
  hosts:
    - host: pds.yunmotec.net
      paths: ["/"]
resources: {}
persistence:
    enabled: true
    claimName: pdsserverqa